# Generated by Django 5.1.3 on 2024-11-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="event_location",
            field=models.CharField(default="Location not set yet.", max_length=200),
        ),
    ]
