# Generated by Django 5.1.3 on 2024-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.CharField(default="No picture", max_length=400),
        ),
    ]
